# Generated by Django 5.1.7 on 2025-03-30 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('proprietario', 'Proprietário'), ('administrador', 'Administrador')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_transporte', models.CharField(choices=[('Terrestre', 'Terrestre'), ('Ferroviário', 'Ferroviário'), ('Marítimo', 'Marítimo')], default='Terrestre', max_length=50)),
                ('horario', models.TimeField()),
                ('nr_rota', models.CharField(blank=True, max_length=255, unique=True)),
                ('lugares', models.IntegerField(default=0)),
                ('valor_passagem', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('tipo_transporte', models.CharField(choices=[('terrestre', 'Terrestre'), ('ferroviario', 'Ferroviário'), ('maritimo', 'Marítimo')], max_length=20)),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rota')),
            ],
        ),
        migrations.CreateModel(
            name='Paragem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paragem', models.CharField(max_length=255)),
                ('ordem', models.IntegerField()),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rota')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('autocarro', 'Autocarro'), ('camiao', 'Camião')], max_length=10)),
                ('modelo', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField()),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('renda_diaria', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('renda_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proprietario')),
            ],
        ),
        migrations.CreateModel(
            name='VeiculoRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rota')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculo')),
            ],
        ),
    ]
