# Generated by Django 5.1.7 on 2025-04-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
