# Generated by Django 5.1.7 on 2025-04-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reserva_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='valor_passagem',
        ),
        migrations.AddField(
            model_name='rota',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
