# Generated by Django 5.1.7 on 2025-04-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='proprietario',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='proprietario',
        ),
        migrations.AddField(
            model_name='contrato',
            name='nome_proprietario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='nome_proprietario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
