# Generated by Django 5.1.7 on 2025-04-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_reserva_bagagem_kg_reserva_contacto_emergencia_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='embarcado',
            field=models.BooleanField(default=False),
        ),
    ]
