# Generated by Django 5.1.7 on 2025-04-18 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_reserva_embarcado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateField(auto_now_add=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (Kg)')),
                ('ref_bagagem', models.CharField(max_length=100, unique=True, verbose_name='Referência da Bagagem')),
                ('embarcado', models.BooleanField(default=False)),
                ('nome_remetente', models.CharField(max_length=255)),
                ('telefone_remetente', models.CharField(max_length=20)),
                ('nome_receptor', models.CharField(max_length=255)),
                ('telefone_receptor', models.CharField(max_length=20)),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rota')),
            ],
        ),
    ]
