# Generated by Django 5.1.7 on 2025-04-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_encomenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='tipo_transporte',
        ),
    ]
