# Generated by Django 5.1.7 on 2025-05-03 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_configuracaosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agendaviagem'),
        ),
    ]
