# Generated by Django 5.1.7 on 2025-10-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_reserva_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome_usuario',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
