# Generated by Django 5.1.7 on 2025-11-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_bilhete'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilhete',
            name='bagagem_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
