# Generated by Django 5.1.7 on 2025-04-06 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_veiculo_status_delete_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='lugares',
        ),
        migrations.RemoveField(
            model_name='rota',
            name='valor',
        ),
        migrations.AddField(
            model_name='rota',
            name='valor_passagem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='rota',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.veiculo'),
        ),
        migrations.AlterField(
            model_name='rota',
            name='nr_rota',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rota',
            name='tipo_transporte',
            field=models.CharField(choices=[('terrestre', 'Terrestre'), ('ferroviario', 'Ferroviário'), ('maritimo', 'Marítimo')], max_length=20),
        ),
    ]
