# Generated by Django 5.1.7 on 2025-04-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_rota_lugares_remove_rota_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_bilhete',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usado',
            field=models.BooleanField(default=False),
        ),
    ]
