# Generated by Django 5.1.7 on 2025-04-07 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_reserva_codigo_bilhete_reserva_usado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='paragem_embarque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paragem'),
        ),
        migrations.AlterField(
            model_name='paragem',
            name='ordem',
            field=models.PositiveIntegerField(),
        ),
    ]
