# Generated by Django 5.1.7 on 2025-04-08 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reserva_paragem_embarque_alter_paragem_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotas_motorista', to='core.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('proprietario', 'Proprietário'), ('motorista', 'Motorista')], max_length=20),
        ),
    ]
