# Generated by Django 5.1.7 on 2025-04-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rota_motorista_alter_usuario_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='tipo_rota',
            field=models.CharField(choices=[('urbana', 'Urbana'), ('interprovincial', 'Interprovincial')], default='urbana', max_length=20),
        ),
    ]
