# Generated by Django 5.1.7 on 2025-04-18 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rota_tipo_rota'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_viagem',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
