# Generated by Django 5.1.7 on 2025-04-18 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_reserva_data_viagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='core.rota')),
            ],
        ),
    ]
