# Generated by Django 5.1.7 on 2025-04-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_agendaviagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='bagagem_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='contacto_emergencia_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='contacto_emergencia_telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nome_passageiro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='ref_bagagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefone_passageiro',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
