# Generated by Django 5.1.7 on 2025-04-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_rota_tipo_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='tipo_transporte',
            field=models.CharField(choices=[('terrestre', 'Terrestre'), ('ferroviario', 'Ferroviário'), ('maritimo', 'Marítimo')], default='terrestre', max_length=20),
        ),
    ]
