# Generated by Django 5.1.7 on 2025-05-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rota_tipo_transporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao_reutilizacao', models.DecimalField(decimal_places=2, default=0.1, help_text='Percentagem da comissão sobre reutilização (ex: 0.10 = 10%)', max_digits=5)),
            ],
        ),
    ]
