# Generated by Django 5.1.7 on 2025-11-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_usuario_nome_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
