# Generated by Django 5.1.7 on 2025-11-10 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_reserva_nome_alter_reserva_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_passageiro', models.CharField(max_length=255)),
                ('telefone_passageiro', models.CharField(max_length=15)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('embarcado', models.BooleanField(default=False)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilhetes', to='core.reserva')),
            ],
        ),
    ]
