# Generated by Django 5.1.7 on 2025-11-12 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_bilhete_bagagem_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='data_rota',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
