# Generated by Django 5.1.7 on 2025-11-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rota_data_rota'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilhete',
            name='data_viagem',
            field=models.DateField(blank=True, null=True),
        ),
    ]
