# Generated by Django 5.1.7 on 2025-11-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
